kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: local-csi-driver
  namespace: local-csi-driver
  labels:
    app.kubernetes.io/name: local-csi-driver
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: local-csi-driver
      app.kubernetes.io/instance: local-csi-driver
  template:
    metadata:
      labels:
        app.kubernetes.io/name: local-csi-driver
        app.kubernetes.io/instance: local-csi-driver
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: local-csi-driver
      tolerations:
      - operator: Exists
      containers:
      - name: local-csi-driver
        securityContext:
          privileged: true
        image: docker.io/scylladb/k8s-local-volume-provisioner:latest
        imagePullPolicy: IfNotPresent
        args:
        - --endpoint=unix://csi/csi.sock
        - --node-name=$(KUBE_NODE_NAME)
        - --volumes-dir=/mnt/volumes
        - --v=4
        env:
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: kubelet-dir
          mountPath: /var/lib/kubelet
          mountPropagation: "Bidirectional"
        - name: plugin-dir
          mountPath: /csi
        - name: volumes-dir
          mountPath: /mnt/volumes
        ports:
        - name: healthz
          containerPort: 9809
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: healthz
          initialDelaySeconds: 10
          timeoutSeconds: 3
          periodSeconds: 2
          failureThreshold: 5
      - name: csi-driver-registrar
        image:  k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.6.1
        imagePullPolicy: IfNotPresent
        args:
        - --csi-address=/csi/csi.sock
        - --kubelet-registration-path=/var/lib/kubelet/plugins/local.csi.scylladb.com/csi.sock
        volumeMounts:
        - name: plugin-dir
          mountPath: /csi
        - name: registration-dir
          mountPath: /registration
      - name: liveness-probe
        image: k8s.gcr.io/sig-storage/livenessprobe:v2.8.0
        imagePullPolicy: IfNotPresent
        args:
        - --csi-address=/csi/csi.sock
        - --health-port=9809
        - --v=2
        volumeMounts:
        - name: plugin-dir
          mountPath: /csi
      - name: csi-provisioner
        image: k8s.gcr.io/sig-storage/csi-provisioner:v3.3.0
        imagePullPolicy: IfNotPresent
        args:
        - --csi-address=/csi/csi.sock
        - --v=2
        - --node-deployment
        - --feature-gates=Topology=true
        - --immediate-topology=false
        - --enable-capacity
        - --capacity-poll-interval=30s
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: plugin-dir
          mountPath: /csi
      volumes:
      - name: kubelet-dir
        hostPath:
          path: /var/lib/kubelet
          type: Directory
      - name: plugin-dir
        hostPath:
          path: /var/lib/kubelet/plugins/local.csi.scylladb.com/
          type: DirectoryOrCreate
      - name: registration-dir
        hostPath:
          path: /var/lib/kubelet/plugins_registry/
          type: Directory
      - name: volumes-dir
        hostPath:
          path: /mnt/persistent-volume
          type: Directory
